In [ ]:
import pandas as pd

df_tue = pd.read_csv('Tuesday-WorkingHours.pcap_ISCX.csv')
df_fri1 = pd.read_csv('Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv')
df_fri = pd.read_csv('Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv')


In [ ]:
df_tue.head()

Destination Port   Flow Duration   Total Fwd Packets  \
0                 88             640                   7   
1                 88             900                   9   
2                 88            1205                   7   
3                 88             511                   7   
4                 88             773                   9   

    Total Backward Packets  Total Length of Fwd Packets  \
0                        4                          440   
1                        4                          600   
2                        4                         2776   
3                        4                          452   
4                        4                          612   

    Total Length of Bwd Packets   Fwd Packet Length Max  \
0                           358                     220   
1                          2944                     300   
2                          2830                    1388   
3                           370                     226   
4                          2944                     306   

    Fwd Packet Length Min   Fwd Packet Length Mean   Fwd Packet Length Std  \
0                       0                62.857143              107.349008   
1                       0                66.666667              132.287566   
2                       0               396.571429              677.274651   
3                       0                64.571429              110.276708   
4                       0                68.000000              134.933317   

   ...   min_seg_size_forward  Active Mean   Active Std   Active Max  \
0  ...                   20.0          0.0          0.0          0.0   
1  ...                   20.0          0.0          0.0          0.0   
2  ...                   20.0          0.0          0.0          0.0   
3  ...                   20.0          0.0          0.0          0.0   
4  ...                   20.0          0.0          0.0          0.0   

    Active Min  Idle Mean   Idle Std   Idle Max   Idle Min   Label  
0          0.0        0.0        0.0        0.0        0.0  BENIGN  
1          0.0        0.0        0.0        0.0        0.0  BENIGN  
2          0.0        0.0        0.0        0.0        0.0  BENIGN  
3          0.0        0.0        0.0        0.0        0.0  BENIGN  
4          0.0        0.0        0.0        0.0        0.0  BENIGN  

[5 rows x 79 columns]

In [ ]:
df_fri1.head()

Destination Port   Flow Duration   Total Fwd Packets  \
0              54865               3                   2   
1              55054             109                   1   
2              55055              52                   1   
3              46236              34                   1   
4              54863               3                   2   

    Total Backward Packets  Total Length of Fwd Packets  \
0                        0                           12   
1                        1                            6   
2                        1                            6   
3                        1                            6   
4                        0                           12   

    Total Length of Bwd Packets   Fwd Packet Length Max  \
0                             0                       6   
1                             6                       6   
2                             6                       6   
3                             6                       6   
4                             0                       6   

    Fwd Packet Length Min   Fwd Packet Length Mean   Fwd Packet Length Std  \
0                       6                      6.0                     0.0   
1                       6                      6.0                     0.0   
2                       6                      6.0                     0.0   
3                       6                      6.0                     0.0   
4                       6                      6.0                     0.0   

   ...   min_seg_size_forward  Active Mean   Active Std   Active Max  \
0  ...                     20          0.0          0.0            0   
1  ...                     20          0.0          0.0            0   
2  ...                     20          0.0          0.0            0   
3  ...                     20          0.0          0.0            0   
4  ...                     20          0.0          0.0            0   

    Active Min  Idle Mean   Idle Std   Idle Max   Idle Min   Label  
0            0        0.0        0.0          0          0  BENIGN  
1            0        0.0        0.0          0          0  BENIGN  
2            0        0.0        0.0          0          0  BENIGN  
3            0        0.0        0.0          0          0  BENIGN  
4            0        0.0        0.0          0          0  BENIGN  

[5 rows x 79 columns]

In [ ]:
df_fri.head()

Destination Port   Flow Duration   Total Fwd Packets  \
0                 22         1266342                  41   
1                 22         1319353                  41   
2                 22             160                   1   
3                 22         1303488                  41   
4              35396              77                   1   

    Total Backward Packets  Total Length of Fwd Packets  \
0                       44                         2664   
1                       44                         2664   
2                        1                            0   
3                       42                         2728   
4                        2                            0   

    Total Length of Bwd Packets   Fwd Packet Length Max  \
0                          6954                     456   
1                          6954                     456   
2                             0                       0   
3                          6634                     456   
4                             0                       0   

    Fwd Packet Length Min   Fwd Packet Length Mean   Fwd Packet Length Std  \
0                       0                64.975610              109.864573   
1                       0                64.975610              109.864573   
2                       0                 0.000000                0.000000   
3                       0                66.536585              110.129945   
4                       0                 0.000000                0.000000   

   ...   min_seg_size_forward  Active Mean   Active Std   Active Max  \
0  ...                     32          0.0          0.0            0   
1  ...                     32          0.0          0.0            0   
2  ...                     32          0.0          0.0            0   
3  ...                     32          0.0          0.0            0   
4  ...                     32          0.0          0.0            0   

    Active Min  Idle Mean   Idle Std   Idle Max   Idle Min   Label  
0            0        0.0        0.0          0          0  BENIGN  
1            0        0.0        0.0          0          0  BENIGN  
2            0        0.0        0.0          0          0  BENIGN  
3            0        0.0        0.0          0          0  BENIGN  
4            0        0.0        0.0          0          0  BENIGN  

[5 rows x 79 columns]

In [ ]:
df_tue.columns = df_tue.columns.str.strip()

df_tue['Label'].value_counts()



Label
BENIGN         267003
FTP-Patator      7938
SSH-Patator      2987
Name: count, dtype: int64

In [ ]:
df_fri1.columns = df_tue.columns.str.strip()

df_fri1['Label'].value_counts()

Label
DDoS      128027
BENIGN     97718
Name: count, dtype: int64

In [ ]:
df_fri.columns = df_tue.columns.str.strip()

df_fri['Label'].value_counts()

Label
PortScan    158930
BENIGN      127537
Name: count, dtype: int64

In [ ]:
combined_df = pd.concat([df_tue, df_fri1, df_fri], ignore_index=True)

combined_df = combined_df.sample(frac=1).reset_index(drop=True)

combined_df.to_csv('combined_network_data.csv', index=False)

print("Combined CSV saved as combined_network_data.csv")


Combined CSV saved as combined_network_data.csv


In [ ]:
combined_df = pd.read_csv('combined_network_data.csv')

combined_df.head()


Destination Port  Flow Duration  Total Fwd Packets  Total Backward Packets  \
0                80      115790472                 16                      14   
1                80         256542                  3                       6   
2               443         629851                  3                       0   
3               443       60564629                 15                      14   
4                21        9898712                  9                      15   

   Total Length of Fwd Packets  Total Length of Bwd Packets  \
0                          449                          979   
1                           26                        11607   
2                           43                            0   
3                          937                         5588   
4                          101                          188   

   Fwd Packet Length Max  Fwd Packet Length Min  Fwd Packet Length Mean  \
0                    438                      0               28.062500   
1                     20                      0                8.666667   
2                     31                      6               14.333333   
3                    557                      0               62.466667   
4                     22                      0               11.222222   

   Fwd Packet Length Std  ...  min_seg_size_forward  Active Mean   Active Std  \
0             109.317561  ...                  20.0  34230.81818  39849.19309   
1              10.263203  ...                  20.0      0.00000      0.00000   
2              14.433757  ...                  20.0      0.00000      0.00000   
3             147.196112  ...                  20.0  79414.33333  79911.59331   
4               8.828615  ...                  32.0      0.00000      0.00000   

   Active Max  Active Min   Idle Mean     Idle Std    Idle Max   Idle Min  \
0    154380.0     22006.0  10000000.0  24426.53583  10100000.0  9999414.0   
1         0.0         0.0         0.0      0.00000         0.0        0.0   
2         0.0         0.0         0.0      0.00000         0.0        0.0   
3    242533.0     46665.0   9995824.5  10405.63900  10000000.0  9974603.0   
4         0.0         0.0         0.0      0.00000         0.0        0.0   

         Label  
0       BENIGN  
1         DDoS  
2       BENIGN  
3       BENIGN  
4  FTP-Patator  

[5 rows x 79 columns]

In [ ]:
combined_df.columns = df_tue.columns.str.strip()

combined_df['Label'].value_counts()

Label
BENIGN         492258
PortScan       158930
DDoS           128027
FTP-Patator      7938
SSH-Patator      2987
Name: count, dtype: int64

In [ ]:
import numpy as np

combined_df.replace([np.inf, -np.inf], np.nan, inplace=True)
combined_df.dropna(inplace=True)


In [ ]:
missing_values = combined_df.isnull().sum()
missing_values = missing_values[missing_values > 0]

print("Columns with missing values:\n")
print(missing_values)


Columns with missing values:

Series([], dtype: int64)


In [ ]:
print(combined_df.dtypes)


Destination Port                 int64
Flow Duration                    int64
Total Fwd Packets                int64
Total Backward Packets           int64
Total Length of Fwd Packets      int64
                                ...   
Idle Mean                      float64
Idle Std                       float64
Idle Max                       float64
Idle Min                       float64
Label                           object
Length: 79, dtype: object


In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
combined_df['label_encoded'] = le.fit_transform(combined_df['Label'])


In [ ]:
numeric_df = combined_df.select_dtypes(include=['int64', 'float64'])

numeric_df['label_encoded'] = combined_df['label_encoded']

correlation = numeric_df.corr()

correlation_with_label = correlation['label_encoded'].sort_values(ascending=False)

print(correlation_with_label)


label_encoded             1.000000
PSH Flag Count            0.534416
Bwd Packets/s             0.229545
Init_Win_bytes_forward    0.176163
Down/Up Ratio             0.086239
                            ...   
Fwd Avg Packets/Bulk           NaN
Fwd Avg Bulk Rate              NaN
Bwd Avg Bytes/Bulk             NaN
Bwd Avg Packets/Bulk           NaN
Bwd Avg Bulk Rate              NaN
Name: label_encoded, Length: 79, dtype: float64


In [ ]:
important_features = correlation_with_label[correlation_with_label.abs() > 0.16].index.tolist()

print("Selected Features:", important_features)


Selected Features: ['label_encoded', 'PSH Flag Count', 'Bwd Packets/s', 'Init_Win_bytes_forward', 'URG Flag Count', 'Bwd IAT Max', 'Avg Fwd Segment Size', 'Fwd Packet Length Mean', 'Fwd IAT Total', 'Flow Duration', 'Bwd IAT Total', 'ACK Flag Count', 'Bwd Packet Length Min', 'Min Packet Length']


In [ ]:
selected_features = [
    'PSH Flag Count',
    'Bwd Packets/s',
    'Init_Win_bytes_forward',
    'Fwd IAT Total',
    'URG Flag Count',
    'Flow Duration',
    'Bwd IAT Total',
    'ACK Flag Count',
    'Bwd Packet Length Min',
    'Min Packet Length',
    'Label'
]

combined_df = combined_df[selected_features]


In [ ]:
combined_df['Label'] = le.inverse_transform(combined_df['label_encoded'])


KeyError: 'label_encoded'

In [ ]:
print(combined_df['Label'].value_counts())


Label
BENIGN         491803
PortScan       158804
DDoS           128025
FTP-Patator      7935
SSH-Patator      2987
Name: count, dtype: int64


In [ ]:
combined_df.drop('label_encoded', axis=1, inplace=True)


KeyError: "['label_encoded'] not found in axis"

In [ ]:
print(combined_df.head())

   PSH Flag Count  Bwd Packets/s  Init_Win_bytes_forward  Fwd IAT Total  \
0               1       0.120908                  8192.0      116000000   
1               1      23.387983                  8192.0           1013   
2               0       0.000000                 64240.0         629851   
3               1       0.231158                  8192.0       60600000   
4               1       1.515349                 29200.0        7150677   

   URG Flag Count  Flow Duration  Bwd IAT Total  ACK Flag Count  \
0             0.0      115790472      110000000               0   
1             0.0         256542         256486               0   
2             0.0         629851              0               1   
3             0.0       60564629       60500000               0   
4             0.0        9898712        9898613               0   

   Bwd Packet Length Min  Min Packet Length        Label  
0                      0                  0       BENIGN  
1                      0    

In [ ]:
features_to_scale = [
    'Init_Win_bytes_forward',
    'Bwd Packets/s',
    'Bwd IAT Total',
    'Fwd IAT Total',
    'Flow Duration',
    'Bwd Packet Length Min',
    'Min Packet Length'
]


In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
combined_df[features_to_scale] = scaler.fit_transform(combined_df[features_to_scale])


In [ ]:
combined_df.head()

PSH Flag Count  Bwd Packets/s  Init_Win_bytes_forward  Fwd IAT Total  \
0               1      -0.209423               -0.060456       3.423631   
1               1      -0.208884               -0.060456      -0.393312   
2               0      -0.209426                3.747711      -0.372620   
3               1      -0.209421               -0.060456       1.600696   
4               1      -0.209391                1.366927      -0.158053   

   URG Flag Count  Flow Duration  Bwd IAT Total  ACK Flag Count  \
0             0.0       3.393717       3.710783               0   
1             0.0      -0.397637      -0.319731               0   
2             0.0      -0.385387      -0.329151               1   
3             0.0       1.581429       1.892813               0   
4             0.0      -0.081221       0.034392               0   

   Bwd Packet Length Min  Min Packet Length        Label  
0              -0.501002          -0.579354       BENIGN  
1              -0.501002          -0.579354         DDoS  
2              -0.501002          -0.288724       BENIGN  
3              -0.466108          -0.579354       BENIGN  
4              -0.501002          -0.579354  FTP-Patator

In [ ]:
target_size = 2900

classes_to_balance = ['BENIGN', 'PortScan', 'DDoS', 'FTP-Patator', 'SSH-Patator']

balanced_df = pd.concat([
    combined_df[combined_df['Label'] == cls].sample(n=target_size, random_state=42)
    for cls in classes_to_balance
])

balanced_df = balanced_df.sample(frac=1, random_state=42).reset_index(drop=True)

balanced_df.to_csv("balanced_5class_data.csv", index=False)

print("balanced_5class_data.csv created with 2900 samples per class.")

balanced_5class_data.csv created with 2900 samples per class.


In [ ]:
print("Shape of balanced_df:", balanced_df.shape)

print("\nClass distribution:")
print(balanced_df['Label'].value_counts())


Shape of balanced_df: (14500, 11)

Class distribution:
Label
SSH-Patator    2900
BENIGN         2900
FTP-Patator    2900
PortScan       2900
DDoS           2900
Name: count, dtype: int64


In [ ]:
from sklearn.model_selection import train_test_split

X = balanced_df.drop('Label', axis=1)
y = balanced_df['Label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)


In [ ]:
print("y_train class distribution:")
print(y_train.value_counts())

print("\ny y_test class distribution:")
print(y_test.value_counts())


y_train class distribution:
Label
BENIGN         393442
PortScan       127043
DDoS           102420
FTP-Patator      6348
SSH-Patator      2390
Name: count, dtype: int64

y y_test class distribution:
Label
BENIGN         98361
PortScan       31761
DDoS           25605
FTP-Patator     1587
SSH-Patator      597
Name: count, dtype: int64


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


              precision    recall  f1-score   support

      BENIGN       0.99      0.99      0.99       580
        DDoS       1.00      0.99      1.00       580
 FTP-Patator       0.99      1.00      1.00       580
    PortScan       1.00      1.00      1.00       580
 SSH-Patator       1.00      1.00      1.00       580

    accuracy                           1.00      2900
   macro avg       1.00      1.00      1.00      2900
weighted avg       1.00      1.00      1.00      2900

[[575   1   3   1   0]
 [  4 576   0   0   0]
 [  1   0 579   0   0]
 [  0   0   0 580   0]
 [  1   0   1   0 578]]


In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy Score:", accuracy)


Accuracy Score: 0.9958620689655172


In [ ]:
print(y_test.value_counts())


Label
SSH-Patator    580
DDoS           580
PortScan       580
BENIGN         580
FTP-Patator    580
Name: count, dtype: int64


In [ ]:
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_test_encoded = le.fit_transform(y_test)
y_pred_encoded = le.transform(y_pred)

mse = mean_squared_error(y_test_encoded, y_pred_encoded)
print("Mean Squared Error (MSE):", mse)


Mean Squared Error (MSE): 0.017241379310344827


In [ ]:
sse = mse * len(y_test)
print("Sum of Squared Errors (SSE):", sse)


Sum of Squared Errors (SSE): 492.0


In [ ]:
!pip install joblib


In [ ]:
import joblib
joblib.dump(model, 'network_intrusion_model2.pkl')
print("Model saved as 'network_intrusion_model2.pkl'")


Model saved as 'network_intrusion_model2.pkl'


In [ ]:
model1 = joblib.load('network_intrusion_model2.pkl')
print("Model loaded successfully")


Model loaded successfully


In [ ]:
!pip install scapy joblib


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 19.0 MB/s eta 0:00:00


In [ ]:
from sklearn.preprocessing import StandardScaler
import joblib

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_train)

joblib.dump(scaler, 'scaler.pkl')


['scaler.pkl']

In [ ]:
from google.colab import files
files.download('/content/network_intrusion_model1.pkl')


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
import pandas as pd

df = pd.read_csv('balanced_5class_data.csv')

samples_per_class = 10

balanced_df = df.groupby('Label').apply(lambda x: x.sample(n=samples_per_class, random_state=42)).reset_index(drop=True)

balanced_df.to_csv('balanced_network_data3.csv', index=False)

print("Balanced dataset saved as 'balanced_network_data3.csv'")


Balanced dataset saved as 'balanced_network_data3.csv'


<ipython-input-47-712c1ae12627>:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  balanced_df = df.groupby('Label').apply(lambda x: x.sample(n=samples_per_class, random_state=42)).reset_index(drop=True)


In [ ]:
from google.colab import files

files.download('/content/combined_network_data.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>